/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EnhancedCanvas
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// node_modules/monkey-around/dist/index.mjs
function around(obj, factories) {
  const removers = Object.keys(factories).map((key) => around1(obj, key, factories[key]));
  return removers.length === 1 ? removers[0] : function() {
    removers.forEach((r) => r());
  };
}
function around1(obj, method, createWrapper) {
  const inherited = obj[method], hadOwn = obj.hasOwnProperty(method), original = hadOwn ? inherited : function() {
    return Object.getPrototypeOf(obj)[method].apply(this, arguments);
  };
  let current = createWrapper(original);
  if (inherited)
    Object.setPrototypeOf(current, inherited);
  Object.setPrototypeOf(wrapper, current);
  obj[method] = wrapper;
  return remove;
  function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }
  function remove() {
    if (obj[method] === wrapper) {
      if (hadOwn)
        obj[method] = original;
      else
        delete obj[method];
    }
    if (current === original)
      return;
    current = original;
    Object.setPrototypeOf(wrapper, inherited || Function);
  }
}

// src/CanvasExploder.ts
var import_obsidian2 = require("obsidian");

// src/utils.ts
var import_obsidian = require("obsidian");
function isVersionNewer(currentVersion, oldVersion) {
  var _a, _b;
  if (!currentVersion || !oldVersion)
    return false;
  const parse = (v) => v.split("-")[0].split(".").map(Number);
  const [a, b] = [parse(currentVersion), parse(oldVersion)];
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    const diff = ((_a = a[i]) != null ? _a : 0) - ((_b = b[i]) != null ? _b : 0);
    if (diff)
      return diff > 0;
  }
  return false;
}
function randomId() {
  const array = new Uint8Array(8);
  window.crypto.getRandomValues(array);
  return Array.from(
    array,
    (byte) => byte.toString(16).padStart(2, "0")
  ).join("");
}
function parseTagQuery(input) {
  if (!input.trim())
    return [];
  const groups = input.split(/(?:\s+|^)OR(?:\s+|$)|\|/i);
  const query = [];
  for (const groupStr of groups) {
    const trimmedGroup = groupStr.trim();
    if (!trimmedGroup)
      continue;
    const whitespaceTokens = trimmedGroup.split(/\s+/);
    const group = { include: [], exclude: [] };
    for (let wToken of whitespaceTokens) {
      if (!wToken)
        continue;
      if (wToken.toUpperCase() === "AND")
        continue;
      let isExclude = false;
      if (wToken.startsWith("-")) {
        isExclude = true;
        wToken = wToken.substring(1);
      }
      const tagTokens = wToken.split("#");
      for (const tagToken of tagTokens) {
        if (!tagToken)
          continue;
        const tag = tagToken.toLowerCase().replace(/[,;]+$/, "");
        if (!tag)
          continue;
        if (isExclude) {
          group.exclude.push(tag);
        } else {
          group.include.push(tag);
        }
      }
    }
    if (group.include.length > 0) {
      query.push(group);
    }
  }
  return query;
}
function matchesTagQuery(file, query, metadataCache) {
  if (query.length === 0)
    return false;
  const cache = metadataCache.getFileCache(file);
  if (!cache)
    return false;
  const fileTags = [...(0, import_obsidian.getAllTags)(cache) || []];
  return query.some((group) => matchesGroup(fileTags, group));
}
function matchesGroup(fileTags, group) {
  if (group.include.length === 0)
    return false;
  const normalizedFileTags = fileTags.map((t) => (t.startsWith("#") ? t.substring(1) : t).toLowerCase());
  const allIncluded = group.include.every(
    (qTag) => normalizedFileTags.some((fTag) => fTag === qTag || fTag.startsWith(`${qTag}/`))
  );
  if (!allIncluded)
    return false;
  const anyExcluded = group.exclude.some(
    (qTag) => normalizedFileTags.some((fTag) => fTag === qTag || fTag.startsWith(`${qTag}/`))
  );
  return !anyExcluded;
}

// src/CanvasExploder.ts
var HEADING_LIMIT = 10;
var COMPACT_HEIGHT = 50;
var LEAF_HEIGHT = 170;
var DEFAULT_WIDTH = 400;
var MAX_HEIGHT = 600;
var GAP_Y = 20;
var GAP_X = 20;
var CanvasExploder = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  checkAndAddMenu(menu, title) {
    const activeView = this.plugin.app.workspace.getActiveViewOfType(import_obsidian2.ItemView);
    if (activeView && activeView.getViewType() === "canvas") {
      const canvas = activeView.canvas;
      if (canvas) {
        const selection = canvas.selection;
        if (selection.size === 1) {
          const node = selection.values().next().value;
          if (node && node.file) {
            menu.addItem((item) => {
              item.setTitle(title).onClick(() => {
                void this.explodeFileNode(canvas, node);
              });
            });
          } else if (node && node.text !== void 0) {
            menu.addItem((item) => {
              item.setTitle(title).onClick(() => {
                void this.explodeTextNode(canvas, node);
              });
            });
          }
        }
      }
    }
  }
  /**
   * Adds the "Split Card by Headings" menu item for text nodes.
   * Called from main.ts when a text node context menu is shown.
   */
  addTextNodeMenu(menu, node) {
    const activeView = this.plugin.app.workspace.getActiveViewOfType(import_obsidian2.ItemView);
    if (!activeView || activeView.getViewType() !== "canvas")
      return;
    const canvas = activeView.canvas;
    if (!canvas)
      return;
    menu.addItem((item) => {
      item.setTitle("Split by headings").onClick(() => {
        void this.explodeTextNode(canvas, node);
      });
    });
  }
  sanitizeHeading(rawHeading) {
    let text = rawHeading.replace(/\[\[|\]\]/g, "");
    text = text.replace(/[[\](){}<>|#:]/g, " ");
    text = text.replace(/\s+/g, " ");
    return text.trim();
  }
  /**
   * Parses raw markdown text into structured sections based on headings.
   */
  parseMarkdownHeadings(rawText) {
    const lines = rawText.split(/\r?\n/);
    const sections = [];
    const preamble = [];
    let currentSection = null;
    const headingRegex = /^(#{1,6})\s+(.*)/;
    for (const line of lines) {
      const match = line.match(headingRegex);
      if (match) {
        if (currentSection) {
          sections.push({
            level: currentSection.level,
            content: currentSection.lines.join("\n")
          });
        }
        currentSection = {
          level: match[1].length,
          // Number of hashes
          lines: [line]
          // Keep the heading in the content
        };
      } else if (currentSection) {
        currentSection.lines.push(line);
      } else {
        preamble.push(line);
      }
    }
    if (currentSection) {
      sections.push({
        level: currentSection.level,
        content: currentSection.lines.join("\n")
      });
    }
    const preambleText = preamble.join("\n").trim();
    if (preambleText && sections.length > 0) {
      sections.unshift({ level: sections[0].level, content: preambleText });
    }
    return sections;
  }
  /**
   * Deconstructs a single file node into a hierarchical tree of connected nodes representing its internal headings,
   * replacing the original node to visualize the document's structure directly on the canvas.
   */
  explodeFileNode(canvas, originalNode) {
    var _a;
    const targetFile = originalNode.file;
    if (!targetFile)
      return;
    const cache = this.plugin.app.metadataCache.getFileCache(targetFile);
    if (!cache || !cache.headings || cache.headings.length === 0) {
      new import_obsidian2.Notice(`File "${targetFile.basename}" does not contain any headings to explode.`);
      return;
    }
    const sections = cache.headings.map((h) => ({ level: h.level, heading: h.heading }));
    const firstHeadingLine = cache.headings[0].position.start.line;
    if ((_a = cache.sections) == null ? void 0 : _a.some((s) => s.type !== "yaml" && s.position.start.line < firstHeadingLine)) {
      sections.unshift({ level: sections[0].level });
    }
    const createdCount = this.buildSectionTree(
      canvas,
      originalNode,
      sections,
      (section) => ({
        type: "file",
        file: targetFile.path,
        // ponytail: no subpath can target "before the first heading", so the
        // preamble node embeds the whole note (preamble renders at the top).
        // Explicit undefined overrides any subpath inherited from originalData.
        subpath: section.heading === void 0 ? void 0 : `#${this.sanitizeHeading(section.heading)}`
      }),
      COMPACT_HEIGHT
    );
    new import_obsidian2.Notice(`Explosion complete, created ${createdCount} nodes.`);
  }
  /**
   * Shared explode core: lays out one node per section (indented by heading
   * level), connects each section to its nearest shallower parent, then swaps
   * the original node for the new tree and selects it.
   *
   * @param nodePayload - Per-section node fields (e.g. file+subpath, or text).
   * @param fallbackLeafHeight - Leaf height when the original node has no usable height.
   * @returns The number of nodes created.
   */
  buildSectionTree(canvas, originalNode, sections, nodePayload, fallbackLeafHeight) {
    var _a, _b;
    const isCompactMode = sections.length > HEADING_LIMIT;
    const baseX = originalNode.x;
    let currentY = originalNode.y;
    const originalHeight = originalNode.height;
    const width = Math.max((_a = originalNode.width) != null ? _a : 0, DEFAULT_WIDTH);
    const minLevel = Math.min(...sections.map((s) => s.level));
    const currentData = canvas.getData();
    const originalData = (_b = currentData.nodes.find((n) => n.id === originalNode.id)) != null ? _b : {};
    const nodeStack = [];
    const newNodesData = [];
    const newEdgesData = [];
    for (let i = 0; i < sections.length; i++) {
      const section = sections[i];
      const nextSection = sections[i + 1];
      const isParent = nextSection && nextSection.level > section.level;
      let nodeHeight;
      if (isParent) {
        nodeHeight = COMPACT_HEIGHT;
      } else if (isCompactMode) {
        nodeHeight = LEAF_HEIGHT;
      } else {
        nodeHeight = typeof originalHeight === "number" && originalHeight > COMPACT_HEIGHT ? Math.min(MAX_HEIGHT, originalHeight) : fallbackLeafHeight;
      }
      const levelOffset = section.level - minLevel;
      const currentX = baseX + levelOffset * (width + GAP_X);
      const newNodeId = randomId();
      newNodesData.push({
        ...originalData,
        ...nodePayload(section),
        id: newNodeId,
        x: currentX,
        y: currentY,
        width,
        height: nodeHeight
      });
      while (nodeStack.length > 0) {
        const lastEntry = nodeStack[nodeStack.length - 1];
        if (lastEntry.level >= section.level) {
          nodeStack.pop();
        } else {
          break;
        }
      }
      if (nodeStack.length > 0) {
        const parentEntry = nodeStack[nodeStack.length - 1];
        newEdgesData.push({
          id: randomId(),
          fromNode: parentEntry.nodeId,
          fromSide: "bottom",
          toNode: newNodeId,
          toSide: "left"
        });
      }
      nodeStack.push({
        level: section.level,
        nodeId: newNodeId
      });
      currentY += nodeHeight + GAP_Y;
    }
    currentData.nodes = currentData.nodes.filter((n) => n.id !== originalNode.id);
    currentData.edges = currentData.edges.filter(
      (e) => e.fromNode !== originalNode.id && e.toNode !== originalNode.id
    );
    currentData.nodes.push(...newNodesData);
    currentData.edges.push(...newEdgesData);
    canvas.setData(currentData);
    canvas.requestSave(false);
    const newNodeIds = new Set(newNodesData.map((n) => n.id));
    canvas.deselectAll();
    for (const [id, node] of canvas.nodes) {
      if (newNodeIds.has(id)) {
        canvas.select(node);
      }
    }
    canvas.zoomToSelection();
    return newNodesData.length;
  }
  /**
   * Deconstructs a single text node into a hierarchical tree of connected nodes representing its internal headings,
   * replacing the original node to visualize the card's structure directly on the canvas.
   */
  explodeTextNode(canvas, originalNode) {
    var _a;
    const sections = this.parseMarkdownHeadings((_a = originalNode.text) != null ? _a : "");
    if (sections.length === 0) {
      new import_obsidian2.Notice("No headings found to split.");
      return;
    }
    const createdCount = this.buildSectionTree(
      canvas,
      originalNode,
      sections,
      (section) => ({
        type: "text",
        text: section.content
      }),
      LEAF_HEIGHT
    );
    new import_obsidian2.Notice(`Split complete, created ${createdCount} cards.`);
  }
};

// src/SendToCanvas.ts
var import_obsidian3 = require("obsidian");
var SendToCanvas = class {
  constructor(plugin) {
    this.selectedCanvas = null;
    this.statusBarItemEl = null;
    this.plugin = plugin;
  }
  handleSendToCanvas() {
    const currentFile = this.getCurrentMarkdownFile();
    if (!currentFile) {
      new import_obsidian3.Notice("Please open a Markdown file to send to the Canvas.");
      return;
    }
    this.promptCanvasSelectionAndInsert(currentFile);
  }
  handleSendToSelectedCanvas() {
    const currentFile = this.getCurrentMarkdownFile();
    if (!currentFile) {
      new import_obsidian3.Notice("Please open a Markdown file to send to the Canvas.");
      return;
    }
    if (this.selectedCanvas) {
      void this.addFileNodeToCanvas(currentFile, this.selectedCanvas);
      new import_obsidian3.Notice(`Using previously selected Canvas: ${this.selectedCanvas.name}`);
    } else {
      new import_obsidian3.Notice(`Failed to send. No Canvas file selected yet.`);
      this.promptCanvasSelectionAndInsert(currentFile);
    }
  }
  getCurrentMarkdownFile() {
    const view = this.plugin.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!(view == null ? void 0 : view.file) || view.file.extension !== "md")
      return null;
    return view.file;
  }
  promptCanvasSelectionAndInsert(targetFile) {
    const canvasFiles = this.getCanvasFiles();
    if (!canvasFiles.length) {
      new import_obsidian3.Notice("No Canvas files found in vault.");
      return;
    }
    const modal = new CanvasFileSuggestModal(
      this.plugin.app,
      canvasFiles,
      (canvasFile) => {
        this.selectedCanvas = canvasFile;
        this.updateStatusBar();
        void this.addFileNodeToCanvas(targetFile, canvasFile);
      }
    );
    modal.open();
  }
  /**
   * Incorporates a file into a Canvas board as a visual node and establishes a bidirectional reference between the document and the workspace.
   *
   * @param targetFile - The file to be added to the visualization.
   * @param canvasFile - The target Canvas file.
   */
  async addFileNodeToCanvas(targetFile, canvasFile) {
    if (!canvasFile || !canvasFile.name)
      return;
    let canvasData;
    const canvasLeaves = this.plugin.app.workspace.getLeavesOfType("canvas");
    const openLeaf = canvasLeaves.find((leaf) => {
      var _a;
      return ((_a = leaf.view.file) == null ? void 0 : _a.path) === canvasFile.path;
    });
    const canvasView = openLeaf ? openLeaf.view : null;
    if (canvasView && canvasView.canvas) {
      canvasData = canvasView.canvas.getData();
    } else {
      const canvasContent = await this.plugin.app.vault.read(canvasFile);
      try {
        canvasData = JSON.parse(canvasContent || '{"nodes":[], "edges":[]}');
      } catch (e) {
        new import_obsidian3.Notice(`Error reading Canvas JSON for ${canvasFile.name}.`);
        console.error("Canvas JSON Parse Error:", e);
        return;
      }
    }
    if (!Array.isArray(canvasData.nodes))
      canvasData.nodes = [];
    if (!Array.isArray(canvasData.edges))
      canvasData.edges = [];
    const existingNode = canvasData.nodes.find((node) => node.type === "file" && node.file === targetFile.path);
    if (existingNode) {
      new import_obsidian3.Notice(`${targetFile.basename} already exists in Canvas.`);
      return;
    }
    const newNode = this.createNodeAtBottom(targetFile, canvasData.nodes);
    canvasData.nodes.push(newNode);
    try {
      if (canvasView && canvasView.canvas) {
        canvasView.canvas.setData(canvasData);
        canvasView.canvas.requestSave();
      } else {
        const updatedContent = JSON.stringify(canvasData, null, 2);
        await this.plugin.app.vault.modify(canvasFile, updatedContent);
      }
      const internalLink = `[[${canvasFile.name}]]`;
      await this.plugin.updateFrontmatter(targetFile, internalLink, "add", "canvas");
      new import_obsidian3.Notice(`Added ${targetFile.basename} to Canvas: ${canvasFile.basename}`);
    } catch (e) {
      new import_obsidian3.Notice(`Failed to add to Canvas: ${canvasFile.name}`);
      console.error("Canvas Modify Error:", e);
    }
  }
  /**
   * Creates a new node for a file at the bottom of the canvas.
   *
   * @param file - The file to create a node for.
   * @param existingNodes - The existing nodes in the canvas.
   * @returns The new node.
   */
  createNodeAtBottom(file, existingNodes) {
    const id = randomId();
    const WIDTH = this.plugin.settings.defaultFileNodeWidth;
    const HEIGHT = this.plugin.settings.defaultFileNodeHeight;
    const GAP = 100;
    const DEFAULT_X = -200;
    const startY = existingNodes.length > 0 ? Math.max(...existingNodes.map((node) => node.y + node.height)) + GAP : -200;
    return {
      id,
      x: DEFAULT_X,
      y: startY,
      width: WIDTH,
      height: HEIGHT,
      type: "file",
      file: file.path
    };
  }
  getCanvasFiles() {
    return this.plugin.app.vault.getFiles().filter((file) => file.extension === "canvas");
  }
  updateStatusBar() {
    const file = this.selectedCanvas;
    if (file) {
      if (!this.statusBarItemEl) {
        this.statusBarItemEl = this.plugin.addStatusBarItem();
        this.statusBarItemEl.addClass("scs-status-canvas");
        this.plugin.registerDomEvent(this.statusBarItemEl, "click", this.handleStatusBarClick.bind(this));
      }
      this.statusBarItemEl.empty();
      this.statusBarItemEl.setText(`Selected Canvas: ${file.name}`);
      this.statusBarItemEl.title = `Click to clear selection: ${file.name}`;
      this.statusBarItemEl.addClass("is-active");
    } else {
      this.clearStatusBar();
    }
  }
  handleStatusBarClick(evt) {
    evt.preventDefault();
    this.clearSelectedCanvas();
  }
  clearSelectedCanvas(showNotice = true) {
    if (this.selectedCanvas) {
      const fileName = this.selectedCanvas.name;
      this.selectedCanvas = null;
      this.clearStatusBar();
      if (showNotice) {
        new import_obsidian3.Notice(`Cleared selected Canvas: ${fileName}`);
      }
    } else if (showNotice) {
      new import_obsidian3.Notice("No Canvas file is currently selected.");
    }
  }
  clearStatusBar() {
    if (this.statusBarItemEl) {
      this.statusBarItemEl.remove();
      this.statusBarItemEl = null;
    }
  }
};
var CanvasFileSuggestModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, files, onSelect) {
    super(app);
    this.files = files;
    this.onSelect = onSelect;
    this.setPlaceholder("Select a Canvas file...");
  }
  getItems() {
    return this.files;
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file, _evt) {
    this.onSelect(file);
    this.close();
  }
};

// src/AdvancedTagSuggestModal.ts
var import_obsidian4 = require("obsidian");
var NODE_GAP = 20;
var WORD_AT_CURSOR = /([-#]?)([^\s#|]*)$/;
var TagSuggest = class extends import_obsidian4.AbstractInputSuggest {
  constructor(app, inputEl, allTags) {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.allTags = allTags;
    this.isOpen = false;
    this.limit = 10;
  }
  open() {
    super.open();
    this.isOpen = true;
  }
  close() {
    super.close();
    this.isOpen = false;
  }
  getSuggestions(value) {
    var _a, _b, _c;
    const cursor = (_a = this.inputEl.selectionStart) != null ? _a : value.length;
    const query = ((_c = (_b = value.substring(0, cursor).match(WORD_AT_CURSOR)) == null ? void 0 : _b[2]) != null ? _c : "").toLowerCase();
    if (!query)
      return [];
    return this.allTags.filter((tag) => tag.toLowerCase().includes(query));
  }
  renderSuggestion(tag, el) {
    el.setText(tag);
  }
  selectSuggestion(tag) {
    var _a;
    const value = this.inputEl.value;
    const cursor = (_a = this.inputEl.selectionStart) != null ? _a : value.length;
    const match = value.substring(0, cursor).match(WORD_AT_CURSOR);
    if (match) {
      const start = cursor - match[0].length;
      const inserted = (match[1] === "-" ? "-#" : "#") + tag.replace(/^#/, "");
      this.setValue(value.substring(0, start) + inserted + value.substring(cursor));
      const pos = start + inserted.length;
      this.inputEl.setSelectionRange(pos, pos);
    }
    this.close();
  }
};
var AdvancedTagSuggestModal = class extends import_obsidian4.Modal {
  constructor(app, plugin, canvas, position) {
    super(app);
    this.plugin = plugin;
    this.canvas = canvas;
    this.position = position;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText("Add notes by tag (Advanced)");
    contentEl.createEl("p", {
      text: "Use space for AND, 'OR' for OR, and '-' for NOT. Example: #tag1 #tag2 -#tag3",
      cls: "setting-item-description"
    });
    const inputContainer = contentEl.createDiv({ cls: "advanced-tag-input-container" });
    this.inputComponent = new import_obsidian4.TextComponent(inputContainer);
    this.inputComponent.setPlaceholder("Enter tag query...");
    this.tagSuggest = new TagSuggest(this.app, this.inputComponent.inputEl, this.getTags());
    this.inputComponent.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.isComposing && !e.defaultPrevented && !this.tagSuggest.isOpen) {
        this.executeImport();
      }
    });
    new import_obsidian4.ButtonComponent(inputContainer).setButtonText("Import").setCta().onClick(() => this.executeImport());
    this.inputComponent.inputEl.focus();
  }
  /**
   * Retrieves all tags from the metadata cache.
   * Note: getTags() can be stale-on-open if the cache hasn't updated recently,
   * but it's the most efficient way to get a list of all existing tags.
   */
  getTags() {
    const tagsMap = this.app.metadataCache.getTags();
    const tags = /* @__PURE__ */ new Set();
    for (const tag of Object.keys(tagsMap)) {
      tags.add(tag);
      this.addParentTags(tag, tags);
    }
    return Array.from(tags).sort((a, b) => a.localeCompare(b));
  }
  addParentTags(tag, tags) {
    const parts = tag.split("/");
    if (parts.length <= 1)
      return;
    for (let depth = 1; depth < parts.length; depth++) {
      tags.add(parts.slice(0, depth).join("/"));
    }
  }
  executeImport() {
    const queryStr = this.inputComponent.getValue();
    if (!queryStr.trim())
      return;
    const query = parseTagQuery(queryStr);
    if (query.length === 0) {
      new import_obsidian4.Notice("Invalid query. Ensure you have at least one inclusion tag (e.g., #tag).");
      return;
    }
    const matchingFiles = this.app.vault.getMarkdownFiles().filter((file) => matchesTagQuery(file, query, this.app.metadataCache)).sort((a, b) => a.path.localeCompare(b.path));
    if (matchingFiles.length === 0) {
      new import_obsidian4.Notice(`No files found matching the query: ${queryStr}`);
      return;
    }
    this.addFilesToCanvas(matchingFiles);
    this.close();
  }
  addFilesToCanvas(files) {
    const width = this.plugin.settings.defaultFileNodeWidth;
    const height = this.plugin.settings.defaultFileNodeHeight;
    const columns = Math.ceil(Math.sqrt(files.length));
    const createdNodes = [];
    files.forEach((file, index) => {
      const x = this.position.x + index % columns * (width + NODE_GAP);
      const y = this.position.y + Math.floor(index / columns) * (height + NODE_GAP);
      try {
        const node = this.canvas.createFileNode({
          file,
          pos: { x, y },
          size: { width, height },
          save: false,
          focus: false
        });
        if (node) {
          createdNodes.push(node);
        }
      } catch (error) {
        console.error(`Enhanced Canvas: failed to create Canvas node for ${file.path}`, error);
      }
    });
    if (createdNodes.length === 0) {
      new import_obsidian4.Notice(`Failed to add notes to Canvas.`);
      return;
    }
    this.selectNodes(createdNodes);
    this.canvas.requestSave();
    new import_obsidian4.Notice(`Added ${createdNodes.length} node${createdNodes.length === 1 ? "" : "s"}.`);
  }
  selectNodes(nodes) {
    this.canvas.deselectAll();
    for (const node of nodes) {
      this.canvas.selection.add(node);
    }
  }
  onClose() {
    var _a;
    (_a = this.tagSuggest) == null ? void 0 : _a.close();
    this.contentEl.empty();
  }
};

// src/CanvasTagImport.ts
var CanvasTagImport = class {
  constructor(plugin) {
    this.patched = false;
    this.menus = /* @__PURE__ */ new WeakSet();
    this.plugin = plugin;
  }
  register() {
    this.plugin.registerLazyPatcher(() => this.patchCanvasCreationMenu());
  }
  patchCanvasCreationMenu() {
    var _a, _b;
    if (this.patched)
      return true;
    const canvas = this.getAnyCanvas();
    if (!((_b = (_a = canvas == null ? void 0 : canvas.constructor) == null ? void 0 : _a.prototype) == null ? void 0 : _b.showCreationMenu))
      return false;
    const plugin = this.plugin;
    const tagImport = this;
    const uninstall = around(canvas.constructor.prototype, {
      showCreationMenu: (next) => {
        return function(menu, position, ...args) {
          const result = next.call(this, menu, position, ...args);
          tagImport.addMenuItem(menu, this, position);
          return result;
        };
      }
    });
    plugin.register(uninstall);
    this.patched = true;
    return true;
  }
  getAnyCanvas() {
    var _a, _b;
    const canvasView = (_b = (_a = this.plugin.app.workspace.getLeavesOfType("canvas")) == null ? void 0 : _a[0]) == null ? void 0 : _b.view;
    if (!canvasView || canvasView.getViewType() !== "canvas")
      return null;
    return canvasView.canvas;
  }
  addMenuItem(menu, canvas, position) {
    if (!canvas || canvas.readonly || this.menus.has(menu))
      return;
    this.menus.add(menu);
    menu.addItem((item) => {
      item.setTitle("Add notes by tag...").setIcon("hashtag").setSection("create").onClick(() => {
        new AdvancedTagSuggestModal(this.plugin.app, this.plugin, canvas, position).open();
      });
    });
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  showReleaseNotes: true,
  previousRelease: "0.0.0",
  enableFrontmatter: true,
  enableCustomCSS: true,
  defaultTextNodeWidth: 250,
  defaultTextNodeHeight: 60,
  defaultFileNodeWidth: 400,
  defaultFileNodeHeight: 400
};

// src/ReleaseNotesModal.ts
var import_obsidian5 = require("obsidian");

// src/releaseNotesData.ts
var firstInstallContent = `
Beyond the original "Property Link" and "Auto Focus" features, recent updates add:

### \u2728 Split by Headings & Add Notes by Tag

- **Split by headings**: right-click a file or text node in Canvas to break it into a tree of nodes, one per heading.
- **Add notes by tag...**: right-click an empty spot on the canvas to bulk-import every note matching a tag query.

### \u2728 Send Note to Canvas

The **"Send to Canvas"** command adds the current note to a Canvas of your choice and writes a "canvas" property to the note, so you can jump back to the board later. That Canvas then becomes the selected one, and **"Send to Selected Canvas"** adds other notes to it without picking the file again.

### \u2728 Auto-Resize Node

Double-click a node's bottom edge to turn on auto-resize: its height then keeps fitting the content as you change the width or edit the text.

[View detailed demo at github](https://github.com/RobertttBS/obsidian-enhanced-canvas)
`;
var fixCursorShiftIssueInStackTabsCanvas = `
> [!bug] Fixed in 1.0.30
> Deleting a folder no longer throws an error, and the notes inside it are cleaned up properly.
> Moving or renaming a canvas no longer leaves stale or duplicate links in note properties.

> [!bug] Fixed in 1.0.29
> Auto-resize and drag-to-create nodes now work in pinned Canvas tabs that haven't been opened yet (Windows).

> [!success] Refactor in 1.0.26\u20131.0.28
> Faster startup sync, fewer redundant frontmatter writes, and more robust property cleanup.

> [!note] Feature in 1.0.25
> "Add notes by tag..." supports multi-tag queries (AND, OR, exclude) with suggestions.

> [!note] Feature in 1.0.24
> Set the default width and height for new nodes in the Enhanced Canvas settings.

> [!note] Feature in 1.0.23
> New "Add notes by tag..." right-click menu option to bulk-import notes by tag.

> [!bug] Fixed in 1.0.22
> Properties now sync for pinned Canvas tabs on Windows 11.

> [!note] Feature in 1.0.21
> Canvas core now supports backlinks, so "Sync Frontmatter" (and the plugin's CSS) can be turned off in the Enhanced Canvas settings.

> [!note] Feature in 1.0.20
> "Focus" now works for Linked Mentions.

> [!note] Feature in 1.0.19
> "Split by headings" now works for Card Nodes.

> [!bug] Fixed in 1.0.18
> Fixes the cursor position shift in Canvas when "stacked tabs" is enabled (a bug in the Canvas core plugin).
`;
var releaseNotesContent = {
  "1.0.30": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.29": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.28": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.27": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.26": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.25": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.24": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.23": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.22": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.21": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.20": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.19": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.18": fixCursorShiftIssueInStackTabsCanvas,
  "1.0.17": firstInstallContent
};

// src/ReleaseNotesModal.ts
var ReleaseNotesModal = class extends import_obsidian5.Modal {
  constructor(app, plugin, version, isNewInstall, previousVersion = "0.0.0") {
    super(app);
    this.renderComponent = new import_obsidian5.Component();
    this.plugin = plugin;
    this.version = version;
    this.isNewInstall = isNewInstall;
    this.previousVersion = previousVersion;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText(
      this.isNewInstall ? "Welcome to Enhanced Canvas" : `Enhanced Canvas updated to v${this.version}`
    );
    contentEl.classList.add("enhanced-canvas-release-notes");
    this.renderComponent.load();
    void this.renderContent();
  }
  async renderContent() {
    const { contentEl } = this;
    let markdownText = "";
    if (this.isNewInstall) {
      markdownText = firstInstallContent;
    } else {
      const notes = [];
      const versions = Object.keys(releaseNotesContent).sort((a, b) => isVersionNewer(a, b) ? -1 : 1);
      for (const v of versions) {
        if (isVersionNewer(v, this.previousVersion) && !isVersionNewer(v, this.version) && !notes.includes(releaseNotesContent[v])) {
          notes.push(releaseNotesContent[v]);
        }
      }
      markdownText = notes.length > 0 ? notes.join("\n\n---\n\n") : "Thank you for updating! This update includes bug fixes.";
    }
    await import_obsidian5.MarkdownRenderer.render(
      this.app,
      markdownText,
      contentEl,
      "/",
      this.renderComponent
    );
    const buttonContainer = contentEl.createDiv({ cls: "release-notes-button-container" });
    buttonContainer.style.marginTop = "20px";
    buttonContainer.style.textAlign = "right";
    new import_obsidian5.ButtonComponent(buttonContainer).setButtonText("Got it").setCta().onClick(() => {
      this.close();
    });
  }
  onClose() {
    this.renderComponent.unload();
    this.contentEl.empty();
    if (this.plugin.settings.previousRelease !== this.version) {
      this.plugin.settings.previousRelease = this.version;
      void this.plugin.saveSettings();
    }
  }
};

// main.ts
function frontmatterValueToArray(value) {
  if (Array.isArray(value)) {
    return value.filter((item) => typeof item === "string" && item.trim() !== "");
  }
  if (typeof value === "string" && value.trim() !== "")
    return [value];
  return [];
}
function writeLinkSet(fm, key, mutate) {
  const existingValue = fm[key];
  const wasString = typeof existingValue === "string" && existingValue.trim() !== "";
  const next = mutate(frontmatterValueToArray(existingValue));
  if (next.length > 0) {
    fm[key] = next.length === 1 && wasString ? next[0] : next;
  } else {
    delete fm[key];
  }
}
function canvasLinkBasename(link) {
  const target = link.trim().replace(/^\[\[(.*)\]\]$/, "$1").split("|")[0].trim();
  const base = target.substring(target.lastIndexOf("/") + 1);
  return base.endsWith(".canvas") ? base.slice(0, -".canvas".length) : base;
}
function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function ensureCanvasKeyOrder(frontmatter, canvasKeys) {
  const keys = Object.keys(frontmatter);
  const canvasIndex = keys.indexOf("canvas");
  if (canvasIndex === -1)
    return;
  const targetKeys = new Set(canvasKeys);
  targetKeys.delete("canvas");
  const firstTargetIndex = keys.findIndex((key) => targetKeys.has(key));
  if (firstTargetIndex === -1 || canvasIndex < firstTargetIndex)
    return;
  const values = { ...frontmatter };
  const reordered = keys.filter((key) => key !== "canvas");
  reordered.splice(reordered.indexOf(keys[firstTargetIndex]), 0, "canvas");
  for (const key of keys)
    delete frontmatter[key];
  for (const key of reordered)
    frontmatter[key] = values[key];
}
var EnhancedCanvas = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.isMetadataClicked = false;
    this.canvasStackInterval = null;
    this.autoHeightUninstaller = null;
    this.dragTempNodeUninstaller = null;
    /**
     * Modifies a file's frontmatter property to ensure a specific value is either 
     * included or excluded while maintaining list integrity.
     */
    this.updateFrontmatter = async (file, link, action, propertyName) => {
      if (!this.settings.enableFrontmatter)
        return;
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        writeLinkSet(fm, propertyName, (links) => {
          const set = new Set(links);
          if (action === "add")
            set.add(link);
          else
            set.delete(link);
          return Array.from(set);
        });
        ensureCanvasKeyOrder(fm, [propertyName]);
      });
    };
    this.ifActiveViewIsCanvas = (commandFn) => (checking) => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.ItemView);
      if ((activeView == null ? void 0 : activeView.getViewType()) !== "canvas") {
        return checking ? false : void 0;
      }
      if (checking)
        return true;
      const canvas = activeView.canvas;
      if (!canvas)
        return;
      return commandFn(canvas);
    };
  }
  /**
   * Scans the selected nodes to identify underlying file references and automatically
   * generates visual connections where valid links exist between files but edges are
   * currently missing on the canvas.
   */
  createMissingEdgesFromLinks(canvas) {
    const selectedNodes = Array.from(canvas.selection);
    const fileNodes = selectedNodes.filter((node) => !!(node == null ? void 0 : node.filePath));
    const resolvedLinks = this.app.metadataCache.resolvedLinks;
    const currentData = canvas.getData();
    const existingEdgesMap = /* @__PURE__ */ new Map();
    currentData.edges.forEach((edge) => {
      existingEdgesMap.set(`${edge.fromNode}->${edge.toNode}`, edge);
    });
    const filePathToNodeMap = /* @__PURE__ */ new Map();
    fileNodes.forEach((node) => {
      if (node.filePath) {
        filePathToNodeMap.set(node.filePath, node);
      }
    });
    const newEdges = [];
    fileNodes.forEach((sourceNode) => {
      if (!sourceNode.filePath)
        return;
      const links = resolvedLinks[sourceNode.filePath];
      if (!links)
        return;
      Object.keys(links).forEach((targetPath) => {
        const targetNode = filePathToNodeMap.get(targetPath);
        if (targetNode && targetNode !== sourceNode) {
          const edgeKey = `${sourceNode.id}->${targetNode.id}`;
          if (!existingEdgesMap.has(edgeKey)) {
            const newEdge = this.createEdge(sourceNode, targetNode);
            newEdges.push(newEdge);
            existingEdgesMap.set(edgeKey, newEdge);
          }
        }
      });
    });
    if (newEdges.length > 0) {
      currentData.edges.push(...newEdges);
      canvas.setData(currentData);
      canvas.requestSave(false);
    }
  }
  /**
   * Recomputes the connection anchor points for all edges contained within the
   * current selection to ensure optimal visual alignment and routing.
   */
  optimizeEdgesBetweenSelectedNodes(canvas) {
    const selectedNodes = Array.from(canvas.selection);
    if (selectedNodes.length < 2)
      return;
    const currentData = canvas.getData();
    const selectedNodeIds = new Set(selectedNodes.map((node) => node.id));
    const nodeById = /* @__PURE__ */ new Map();
    for (const node of currentData.nodes) {
      nodeById.set(node.id, node);
    }
    let didUpdateEdges = false;
    currentData.edges.forEach((edge) => {
      if (selectedNodeIds.has(edge.fromNode) && selectedNodeIds.has(edge.toNode)) {
        const fromNode = nodeById.get(edge.fromNode);
        const toNode = nodeById.get(edge.toNode);
        if (fromNode && toNode) {
          const updatedEdge = this.createEdge(fromNode, toNode);
          if (edge.fromSide !== updatedEdge.fromSide || edge.toSide !== updatedEdge.toSide) {
            edge.fromSide = updatedEdge.fromSide;
            edge.toSide = updatedEdge.toSide;
            didUpdateEdges = true;
          }
        }
      }
    });
    if (didUpdateEdges) {
      canvas.setData(currentData);
      canvas.requestSave(false);
    }
  }
  deleteEdges(canvas) {
    const selectedNodes = Array.from(canvas.selection);
    const selectedNodeIds = new Set(selectedNodes.map((node) => node.id));
    const currentData = canvas.getData();
    currentData.edges = currentData.edges.filter((edge) => {
      return !(selectedNodeIds.has(edge.fromNode) && selectedNodeIds.has(edge.toNode));
    });
    canvas.setData(currentData);
    canvas.requestSave(false);
  }
  /**
   * add 'canvas' and canvas basename properties to the node frontmatter.
   */
  addProperty(node, canvasFile) {
    var _a;
    if (!this.settings.enableFrontmatter)
      return;
    if (!node.file)
      return;
    const file = this.app.vault.getFileByPath(node.file);
    if (!file)
      return;
    const basename = canvasFile.basename;
    const hasCanvasLink = (links) => links.some((link) => canvasLinkBasename(link) === basename);
    const cached = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    if (cached && cached[basename] && hasCanvasLink(frontmatterValueToArray(cached.canvas)))
      return;
    void this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      if (!frontmatter)
        return;
      writeLinkSet(frontmatter, "canvas", (links) => hasCanvasLink(links) ? links : [...links, `[[${canvasFile.name}]]`]);
      if (!frontmatter[basename]) {
        frontmatter[basename] = [];
      }
      ensureCanvasKeyOrder(frontmatter, [basename]);
    });
  }
  /**
   * For JSON nodes only, which are stored in the canvas file, not the canvas node in Obsidian.
   */
  removeProperty(node, canvasFile) {
    var _a;
    if (!this.settings.enableFrontmatter)
      return;
    if (!node.file)
      return;
    const file = this.app.vault.getFileByPath(node.file);
    if (!file)
      return;
    const basename = canvasFile.basename;
    const isCanvasLink = (link) => canvasLinkBasename(link) === basename;
    const cached = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    if (!cached || !(basename in cached) && !frontmatterValueToArray(cached.canvas).some(isCanvasLink))
      return;
    return this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      if (!frontmatter)
        return;
      delete frontmatter[basename];
      writeLinkSet(frontmatter, "canvas", (links) => links.filter((link) => !isCanvasLink(link)));
    });
  }
  /**
   * For JSON nodes only, which are stored in the canvas file, not the canvas node in Obsidian.
   */
  renameProperty(node, oldName, newName) {
    if (!this.settings.enableFrontmatter)
      return;
    if (!node.file)
      return;
    const file = this.app.vault.getFileByPath(node.file);
    if (!file)
      return;
    const getBaseName = (name) => name.substring(name.lastIndexOf("/") + 1);
    newName = getBaseName(newName);
    const oldBaseName = oldName.endsWith(".canvas") ? oldName.slice(0, -7) : oldName;
    const newBaseName = newName.endsWith(".canvas") ? newName.slice(0, -7) : newName;
    void this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      if (!frontmatter)
        return;
      const newFrontmatter = Object.fromEntries(
        Object.entries(frontmatter).map(([key, value]) => [
          key === oldBaseName ? newBaseName : key,
          value
        ])
      );
      Object.keys(frontmatter).forEach((key) => {
        delete frontmatter[key];
      });
      Object.assign(frontmatter, newFrontmatter);
    });
  }
  async removeAllProperty(canvas, canvasData) {
    if (!this.settings.enableFrontmatter)
      return;
    const nodes = canvasData.nodes;
    await Promise.all(nodes.map((node) => {
      if (!(node == null ? void 0 : node.file))
        return;
      return this.removeProperty(node, canvas.view.file);
    }));
  }
  /**
   * Startup sweep: ensures every markdown note referenced by a canvas carries
   * the plugin's frontmatter properties (the `canvas` link list plus one
   * property per canvas holding links to edge-connected notes).
   *
   * The desired state is aggregated across all canvases first, then compared
   * against the metadata cache, so each note gets at most one
   * `processFrontMatter` write — and none at all when it is already up to
   * date, which is the common case on restart.
   */
  async syncAllCanvasProperties() {
    if (!this.settings.enableFrontmatter)
      return;
    const desiredByPath = /* @__PURE__ */ new Map();
    const getDesired = (path) => {
      let desired = desiredByPath.get(path);
      if (!desired) {
        desired = { ensureKeys: /* @__PURE__ */ new Set(), linksByKey: /* @__PURE__ */ new Map() };
        desiredByPath.set(path, desired);
      }
      return desired;
    };
    const canvasFiles = this.app.vault.getFiles().filter((file) => file.extension === "canvas");
    await Promise.all(canvasFiles.map(async (canvasFile) => {
      let canvasData;
      try {
        const content = await this.app.vault.read(canvasFile);
        if (!content || content.trim() === "")
          return;
        canvasData = JSON.parse(content);
      } catch (error) {
        console.error("Enhanced Canvas: Failed to read canvas file", canvasFile.path, error);
        return;
      }
      if (!canvasData)
        return;
      const nodes = Array.isArray(canvasData.nodes) ? canvasData.nodes : [];
      const edges = Array.isArray(canvasData.edges) ? canvasData.edges : [];
      const nodeById = /* @__PURE__ */ new Map();
      for (const node of nodes) {
        nodeById.set(node.id, node);
      }
      for (const node of nodes) {
        if (!(node == null ? void 0 : node.file))
          continue;
        getDesired(node.file).ensureKeys.add(canvasFile.basename);
      }
      for (const edgeData of edges) {
        const fromNode = nodeById.get(edgeData.fromNode);
        const toNode = nodeById.get(edgeData.toNode);
        if (!(fromNode == null ? void 0 : fromNode.file) || !(toNode == null ? void 0 : toNode.file))
          continue;
        if (fromNode.file === toNode.file)
          continue;
        const toFile = this.app.vault.getFileByPath(toNode.file);
        if (!toFile)
          continue;
        const link = this.app.fileManager.generateMarkdownLink(toFile, fromNode.file).replace(/^!(\[\[.*\]\])$/, "$1");
        const desired = getDesired(fromNode.file);
        let links = desired.linksByKey.get(canvasFile.basename);
        if (!links) {
          links = /* @__PURE__ */ new Set();
          desired.linksByKey.set(canvasFile.basename, links);
        }
        links.add(link);
      }
    }));
    await Promise.all(Array.from(desiredByPath.entries()).map(async ([path, desired]) => {
      var _a;
      const file = this.app.vault.getFileByPath(path);
      if (!file || file.extension !== "md")
        return;
      const cached = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
      if (cached) {
        const cachedCanvas = frontmatterValueToArray(cached.canvas);
        const cachedKeys = Object.keys(cached);
        const canvasKeyIndex = cachedKeys.indexOf("canvas");
        const upToDate = Array.from(desired.ensureKeys).every((key) => cachedCanvas.some((link) => canvasLinkBasename(link) === key) && // The key must exist *and* sit below the `canvas` property in the YAML.
        !!cached[key] && canvasKeyIndex !== -1 && canvasKeyIndex < cachedKeys.indexOf(key)) && Array.from(desired.linksByKey.entries()).every(([key, links]) => {
          const existing = frontmatterValueToArray(cached[key]);
          return Array.from(links).every((link) => existing.includes(link));
        });
        if (upToDate)
          return;
      }
      try {
        await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
          if (!frontmatter)
            return;
          writeLinkSet(frontmatter, "canvas", (links) => {
            for (const key of desired.ensureKeys) {
              if (!links.some((link) => canvasLinkBasename(link) === key)) {
                links.push(`[[${key}.canvas]]`);
              }
            }
            return links;
          });
          for (const key of desired.ensureKeys) {
            if (!frontmatter[key]) {
              frontmatter[key] = [];
            }
          }
          for (const [key, links] of desired.linksByKey) {
            writeLinkSet(frontmatter, key, (merged) => {
              for (const link of links) {
                if (!merged.includes(link)) {
                  merged.push(link);
                }
              }
              return merged;
            });
          }
          ensureCanvasKeyOrder(frontmatter, desired.ensureKeys);
        });
      } catch (error) {
        console.error("Enhanced Canvas: Failed to update properties for note", path, error);
      }
    }));
  }
  /** Applies or removes the body CSS class that gates the optional visual styles. */
  toggleCSSClass(enabled) {
    if (enabled) {
      activeDocument.body.classList.add("enhanced-canvas-enabled");
    } else {
      activeDocument.body.classList.remove("enhanced-canvas-enabled");
    }
  }
  /**
   * Patching Canvas internals needs a live Canvas leaf, which may not exist
   * at load time. Runs `patch` now and again on every workspace change that
   * could introduce one, until it reports success — then detaches the retry
   * listeners so the patch can't run twice (see CLAUDE.md). The listeners
   * are also registered for unload cleanup, so a patch that never succeeds
   * leaks nothing.
   */
  registerLazyPatcher(patch) {
    let patched = false;
    const tryToPatch = () => {
      if (patched || !patch())
        return;
      patched = true;
      this.app.workspace.offref(leafEvent);
      this.app.workspace.offref(layoutEvent);
    };
    const leafEvent = this.app.workspace.on("active-leaf-change", tryToPatch);
    const layoutEvent = this.app.workspace.on("layout-change", tryToPatch);
    this.registerEvent(leafEvent);
    this.registerEvent(layoutEvent);
    this.app.workspace.onLayoutReady(tryToPatch);
    tryToPatch();
  }
  /**
   * Registers all core plugin features and performs an initial scan
   * of the vault to process and initialize data from all
   * existing canvas files upon loading.
   */
  async onload() {
    await this.loadSettings();
    this.checkReleaseNotes();
    this.exploder = new CanvasExploder(this);
    this.sendToCanvas = new SendToCanvas(this);
    this.canvasTagImport = new CanvasTagImport(this);
    this.addSettingTab(new EnhancedCanvasSettingTab(this.app, this));
    this.toggleCSSClass(this.settings.enableCustomCSS);
    this.registerPluginCommands();
    this.registerCanvasAutoLink();
    this.registerFileManagerPatches();
    this.registerFocusCanvas();
    this.registerCanvasExploder();
    this.canvasTagImport.register();
    this.registerCanvasNodeAutoHeightPatcher();
    this.registerCanvasDefaultNodeSize();
    this.registerCanvasDragTempNodePatcher();
    try {
      await this.syncAllCanvasProperties();
    } catch (error) {
      console.error("Enhanced Canvas: Error in metadata update loop", error);
      return;
    }
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if (this.canvasStackInterval) {
          window.clearInterval(this.canvasStackInterval);
          this.canvasStackInterval = null;
        }
        if (!leaf)
          return;
        const isStacked = !!activeDocument.querySelector(".workspace-tabs.mod-stacked");
        if (!isStacked)
          return;
        const view = leaf.view;
        if (view.getViewType() !== "canvas")
          return;
        if (typeof view.onResize === "function") {
          view.onResize();
        }
        window.setTimeout(() => {
          if (typeof view.onResize === "function")
            view.onResize();
        }, 200);
        let lastLeft = view.containerEl.getBoundingClientRect().left;
        this.canvasStackInterval = window.setInterval(() => {
          if (!view || !view.containerEl) {
            if (this.canvasStackInterval !== null) {
              window.clearInterval(this.canvasStackInterval);
              this.canvasStackInterval = null;
            }
            return;
          }
          const rect = view.containerEl.getBoundingClientRect();
          if (Math.abs(rect.left - lastLeft) > 2) {
            if (typeof view.onResize === "function") {
              view.onResize();
            }
            lastLeft = rect.left;
          }
        }, 200);
        this.registerInterval(this.canvasStackInterval);
      })
    );
  }
  checkReleaseNotes() {
    try {
      const currentVersion = this.manifest.version;
      const previousVersion = this.settings.previousRelease;
      const isNewInstall = previousVersion === "0.0.0" || !previousVersion;
      if (this.settings.showReleaseNotes) {
        if (isNewInstall || isVersionNewer(currentVersion, previousVersion)) {
          new ReleaseNotesModal(
            this.app,
            this,
            currentVersion,
            isNewInstall,
            previousVersion
          ).open();
        }
      }
    } catch (e) {
      console.error("Failed to show release notes:", e);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Registers patches for the application's FileManager to intercept file deletion
   * and rename operations. This function ensures data integrity by automatically
   * cleaning up references to the modified files throughout the vault before the
   * original operation proceeds.
   */
  registerFileManagerPatches() {
    const filesIn = (file) => {
      if (file instanceof import_obsidian6.TFile)
        return [file];
      const files = [];
      if (file instanceof import_obsidian6.TFolder) {
        import_obsidian6.Vault.recurseChildren(file, (child) => {
          if (child instanceof import_obsidian6.TFile)
            files.push(child);
        });
      }
      return files;
    };
    const deleteFile = async (file) => {
      if (file.deleted === true)
        return;
      const backLinks = this.app.metadataCache.getBacklinksForFile(file);
      if (!backLinks || !backLinks.data)
        return;
      const linkRegexBasename = new RegExp(`\\[\\[${escapeRegExp(file.basename)}(\\|.*)?\\]\\]`);
      const linkRegexFullName = new RegExp(`\\[\\[${escapeRegExp(file.name)}(\\|.*)?\\]\\]`);
      for (const [sourcePath] of backLinks.data.entries()) {
        const sourceFile = this.app.vault.getFileByPath(sourcePath);
        if (!sourceFile || sourceFile.extension !== "md")
          continue;
        await this.app.fileManager.processFrontMatter(sourceFile, (frontmatter) => {
          if (!frontmatter)
            return;
          Object.keys(frontmatter).forEach((key) => {
            if (Array.isArray(frontmatter[key])) {
              frontmatter[key] = frontmatter[key].filter((item) => {
                if (typeof item !== "string")
                  return true;
                return !(linkRegexBasename.test(item) || linkRegexFullName.test(item));
              });
            }
          });
        });
      }
    };
    const deleteCanvasFile = async (file) => {
      if (file.extension !== "canvas")
        return;
      if (file.deleted === true)
        return;
      const content = await this.app.vault.read(file);
      if (!content)
        return;
      const canvasData = JSON.parse(content);
      if (!canvasData)
        return;
      canvasData.nodes.forEach((node) => {
        if (node.type !== "file")
          return;
        void this.removeProperty(node, file);
      });
    };
    const renameCanvasFile = async (file, newPath) => {
      if (file.extension !== "canvas")
        return;
      if (file.deleted === true)
        return;
      const content = await this.app.vault.read(file);
      if (!content)
        return;
      const canvasData = JSON.parse(content);
      if (!canvasData)
        return;
      canvasData.nodes.forEach((node) => {
        if (node.type !== "file")
          return;
        this.renameProperty(node, file.name, newPath);
      });
    };
    const uninstaller = around(this.app.fileManager.constructor.prototype, {
      trashFile(old) {
        return async function(file) {
          for (const child of filesIn(file)) {
            try {
              await deleteCanvasFile(child);
              await deleteFile(child);
            } catch (error) {
              console.error("Enhanced Canvas: cleanup before trash failed", child.path, error);
            }
          }
          return old.call(this, file);
        };
      },
      renameFile(old) {
        return async function(file, newPath) {
          if (file instanceof import_obsidian6.TFile) {
            try {
              await renameCanvasFile(file, newPath);
            } catch (error) {
              console.error("Enhanced Canvas: cleanup before rename failed", file.path, error);
            }
          }
          return old.call(this, file, newPath);
        };
      }
    });
    this.register(uninstaller);
  }
  /**
   * Registers all plugin commands, making them available in the
   * Obsidian command palette.
   *
   * All commands registered here are context-aware and will only be enabled
   * when the active view is a Canvas.
   */
  registerPluginCommands() {
    this.addCommand({
      id: "optimize-edges",
      name: "Adjust edges with shortest path",
      checkCallback: this.ifActiveViewIsCanvas((canvas) => {
        this.optimizeEdgesBetweenSelectedNodes(canvas);
      })
    });
    this.addCommand({
      id: "delete-edges",
      name: "Delete edges between selected nodes",
      checkCallback: this.ifActiveViewIsCanvas((canvas) => {
        this.deleteEdges(canvas);
      })
    });
    this.addCommand({
      id: "add-link-and-optimize-edge",
      name: "Add edges according the links in notes",
      checkCallback: this.ifActiveViewIsCanvas((canvas) => {
        this.createMissingEdgesFromLinks(canvas);
        this.optimizeEdgesBetweenSelectedNodes(canvas);
      })
    });
    this.addCommand({
      id: "remove-canvas-property",
      name: "Remove the property of all nodes in current Canvas",
      checkCallback: this.ifActiveViewIsCanvas((canvas) => {
        void this.removeAllProperty(canvas, canvas.getData());
      })
    });
    this.addCommand({
      id: "send-to-canvas",
      name: "Send to Canvas",
      callback: () => {
        this.sendToCanvas.handleSendToCanvas();
      }
    });
    this.addCommand({
      id: "send-to-selected-canvas",
      name: "Send to Selected Canvas",
      callback: () => {
        this.sendToCanvas.handleSendToSelectedCanvas();
      }
    });
    this.addCommand({
      id: "clear-selected-canvas-file",
      name: "Clear selected Canvas file",
      callback: () => {
        this.sendToCanvas.clearSelectedCanvas();
      }
    });
  }
  /**
   * Registers event listeners to implement a "zoom to node" feature.
   *
   * This function's goal is to automatically focus the canvas on the relevant
   * node when a user navigates to the canvas by clicking a link from another
   * file's metadata/properties panel (e.g., a backlink).
   */
  registerFocusCanvas() {
    let clickedSourceFile = null;
    const handleClick = (evt) => {
      var _a, _b;
      const target = evt.target;
      if (target.closest(".metadata-container") || target.closest(".search-result-container")) {
        this.isMetadataClicked = true;
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.FileView);
        clickedSourceFile = (_b = (_a = activeView == null ? void 0 : activeView.file) == null ? void 0 : _a.path) != null ? _b : null;
        window.setTimeout(() => {
          this.isMetadataClicked = false;
          clickedSourceFile = null;
        }, 500);
      }
    };
    const attachedDocs = /* @__PURE__ */ new WeakSet();
    const attachTo = (doc) => {
      if (attachedDocs.has(doc))
        return;
      attachedDocs.add(doc);
      this.registerDomEvent(doc, "click", handleClick, true);
    };
    attachTo(document);
    this.app.workspace.iterateAllLeaves((leaf) => {
      const doc = leaf.view.containerEl.ownerDocument;
      if (doc)
        attachTo(doc);
    });
    this.registerEvent(
      this.app.workspace.on("window-open", (_workspaceWindow, win) => {
        attachTo(win.document);
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        Promise.resolve().then(async () => {
          if (this.isMetadataClicked == false || !clickedSourceFile)
            return;
          const activeLeaf = this.app.workspace.getActiveViewOfType(import_obsidian6.ItemView);
          if (!activeLeaf || activeLeaf.getViewType() !== "canvas")
            return;
          const prevFile = clickedSourceFile;
          if (!prevFile)
            return;
          const canvas = activeLeaf.canvas;
          if (!canvas)
            return;
          for (const value of canvas.nodes.values()) {
            if ((value == null ? void 0 : value.filePath) === prevFile) {
              canvas.select(value);
            }
          }
          window.setTimeout(() => {
            canvas.zoomToSelection();
          }, 100);
        });
      })
    );
  }
  /**
   * Establishes real-time synchronization to manage frontmatter properties
   * in source files based on their connections within a canvas.
   * This ensures file metadata automatically reflects the
   * visual graph structure as nodes and edges are added, removed, or updated.
   */
  registerCanvasAutoLink() {
    const processNodeUpdate = async (e) => {
      var _a, _b, _c, _d, _e, _f;
      if (!this.settings.enableFrontmatter)
        return;
      const fromNode = (_a = e == null ? void 0 : e.from) == null ? void 0 : _a.node;
      const toNode = (_b = e == null ? void 0 : e.to) == null ? void 0 : _b.node;
      if (!fromNode || !toNode)
        return;
      if (!(fromNode == null ? void 0 : fromNode.filePath))
        return;
      const fromFile = this.app.vault.getFileByPath(fromNode.filePath);
      if (!fromFile)
        return;
      const canvasFile = (_d = (_c = e.canvas) == null ? void 0 : _c.view) == null ? void 0 : _d.file;
      if (!canvasFile)
        return;
      const canvasName = canvasFile.basename;
      const resolvedLinks = this.app.metadataCache.resolvedLinks[fromNode.filePath] || {};
      const fromNodeLinks = Object.keys(resolvedLinks);
      const { edges, nodes } = e.canvas.getData();
      const nodeById = /* @__PURE__ */ new Map();
      const sameFileNodeIds = /* @__PURE__ */ new Set();
      for (const node of nodes) {
        nodeById.set(node.id, node);
        if (node.file === fromNode.filePath)
          sameFileNodeIds.add(node.id);
      }
      if (!sameFileNodeIds.has(fromNode.id))
        return;
      const edgeToNodesFilePathSet = /* @__PURE__ */ new Set();
      for (const edge of edges) {
        if (!sameFileNodeIds.has(edge.fromNode))
          continue;
        const targetNode = nodeById.get(edge.toNode);
        if ((targetNode == null ? void 0 : targetNode.type) === "file")
          edgeToNodesFilePathSet.add(targetNode.file);
      }
      const toLink = (path, file) => this.app.fileManager.generateMarkdownLink(file, path).replace(/^!(\[\[.*\]\])$/, "$1");
      const linksToRemove = [];
      fromNodeLinks.forEach((filePath) => {
        if (edgeToNodesFilePathSet.has(filePath))
          return;
        if (filePath === canvasFile.path)
          return;
        const targetFile = this.app.vault.getFileByPath(filePath);
        if (!targetFile)
          return;
        linksToRemove.push(toLink(filePath, targetFile));
      });
      let linkToAdd = null;
      if (toNode.filePath && fromNode.filePath !== toNode.filePath && edgeToNodesFilePathSet.has(toNode.filePath)) {
        const targetFile = this.app.vault.getFileByPath(toNode.filePath);
        if (targetFile)
          linkToAdd = toLink(toNode.filePath, targetFile);
      }
      const cachedLinks = frontmatterValueToArray(
        (_f = (_e = this.app.metadataCache.getFileCache(fromFile)) == null ? void 0 : _e.frontmatter) == null ? void 0 : _f[canvasName]
      );
      const cacheOutOfDate = linksToRemove.some((link) => cachedLinks.includes(link)) || linkToAdd !== null && !cachedLinks.includes(linkToAdd);
      if (!cacheOutOfDate)
        return;
      await this.app.fileManager.processFrontMatter(fromFile, (fm) => {
        writeLinkSet(fm, canvasName, (links) => {
          const removeSet = new Set(linksToRemove);
          const next = links.filter((link) => !removeSet.has(link));
          if (linkToAdd && !next.includes(linkToAdd))
            next.push(linkToAdd);
          return next;
        });
        ensureCanvasKeyOrder(fm, [canvasName]);
      });
    };
    const pendingEdgeUpdates = /* @__PURE__ */ new Set();
    const flushEdgeUpdates = (0, import_obsidian6.debounce)(() => {
      const pending = Array.from(pendingEdgeUpdates);
      pendingEdgeUpdates.clear();
      for (const edge of pending) {
        void processNodeUpdate(edge);
      }
    }, 500, true);
    const edgeConnectivity = /* @__PURE__ */ new WeakMap();
    const updateTargetNode = (e) => {
      var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l;
      const connectivity = `${(_c = (_b = (_a = e.from) == null ? void 0 : _a.node) == null ? void 0 : _b.id) != null ? _c : ""}:${(_f = (_e = (_d = e.from) == null ? void 0 : _d.node) == null ? void 0 : _e.filePath) != null ? _f : ""}->${(_i = (_h = (_g = e.to) == null ? void 0 : _g.node) == null ? void 0 : _h.id) != null ? _i : ""}:${(_l = (_k = (_j = e.to) == null ? void 0 : _j.node) == null ? void 0 : _k.filePath) != null ? _l : ""}`;
      const previous = edgeConnectivity.get(e);
      if (previous === connectivity)
        return;
      edgeConnectivity.set(e, connectivity);
      if (previous === void 0)
        return;
      pendingEdgeUpdates.add(e);
      flushEdgeUpdates();
    };
    const updateOriginalNode = async (edge) => {
      const toNode = edge.to.node;
      const fromNode = edge.from.node;
      const toFilePath = toNode == null ? void 0 : toNode.filePath;
      const fromFilePath = fromNode == null ? void 0 : fromNode.filePath;
      if (!toFilePath || !fromFilePath)
        return;
      const canvasName = edge.canvas.view.file.basename;
      const file = this.app.vault.getFileByPath(toFilePath);
      if (!file)
        return;
      let link = this.app.fileManager.generateMarkdownLink(file, toFilePath);
      link = link.replace(/^!(\[\[.*\]\])$/, "$1");
      const fromFile = this.app.vault.getFileByPath(fromFilePath);
      if (!fromFile)
        return;
      const { edges, nodes } = edge.canvas.getData();
      const sameFileNodeIds = new Set(
        nodes.filter((node) => node.file === fromFilePath).map((node) => node.id)
      );
      const stillHasConnection = edges.some(
        (e) => sameFileNodeIds.has(e.fromNode) && e.toNode === toNode.id && e.fromNode !== fromNode.id
      );
      if (!stillHasConnection) {
        void this.updateFrontmatter(fromFile, link, "remove", canvasName);
      }
    };
    const removeNodeUpdate = (node) => {
      var _a, _b, _c;
      if (((_a = node == null ? void 0 : node.file) == null ? void 0 : _a.extension) !== "md")
        return;
      const canvasFile = (_c = (_b = node == null ? void 0 : node.canvas) == null ? void 0 : _b.view) == null ? void 0 : _c.file;
      if (!canvasFile || !canvasFile.name)
        return;
      if (node == null ? void 0 : node.filePath) {
        const canvasData = node.canvas.getData();
        const otherNodes = canvasData.nodes.filter(
          (n) => n.file === node.filePath
        );
        if (otherNodes.length === 0) {
          const tmpNode = { file: node.filePath };
          void this.removeProperty(tmpNode, canvasFile);
        }
      }
    };
    const addNodeUpdate = (node) => {
      var _a;
      if (((_a = node == null ? void 0 : node.file) == null ? void 0 : _a.extension) !== "md")
        return;
      const canvasFile = node.canvas.view.file;
      if (!canvasFile || !canvasFile.name)
        return;
      if (node.filePath) {
        const tmpNode = { file: node.filePath };
        void this.addProperty(tmpNode, canvasFile);
      }
    };
    const patchedEdgeConstructors = /* @__PURE__ */ new WeakSet();
    const selfPatched = (edge) => {
      if (patchedEdgeConstructors.has(edge.constructor))
        return;
      patchedEdgeConstructors.add(edge.constructor);
      const uninstaller = around(edge.constructor.prototype, {
        update: (next) => {
          return function(...args) {
            const result = next.call(this, ...args);
            updateTargetNode(this);
            return result;
          };
        }
      });
      this.register(uninstaller);
    };
    let canvasPatched = false;
    const patchCanvas = () => {
      var _a;
      if (canvasPatched)
        return false;
      const canvasView = (_a = this.app.workspace.getLeavesOfType("canvas").find((l) => {
        var _a2;
        return ((_a2 = l.view) == null ? void 0 : _a2.canvas) != null;
      })) == null ? void 0 : _a.view;
      if (!(canvasView == null ? void 0 : canvasView.canvas))
        return false;
      const uninstaller = around(canvasView.canvas.constructor.prototype, {
        removeNode(old) {
          return function(node) {
            const result = old.call(this, node);
            if (this.isClearing !== true) {
              removeNodeUpdate(node);
            }
            return result;
          };
        },
        addNode(old) {
          return function(node) {
            const result = old.call(this, node);
            addNodeUpdate(node);
            return result;
          };
        },
        removeEdge(old) {
          return function(edge) {
            const result = old.call(this, edge);
            if (this.isClearing !== true) {
              void updateOriginalNode(edge);
            }
            return result;
          };
        },
        addEdge(old) {
          return function(edge) {
            const result = old.call(this, edge);
            selfPatched(edge);
            pendingEdgeUpdates.add(edge);
            flushEdgeUpdates();
            return result;
          };
        },
        clear(old) {
          return function() {
            this.isClearing = true;
            const result = old.call(this);
            queueMicrotask(() => {
              this.isClearing = false;
            });
            return result;
          };
        }
      });
      this.register(uninstaller);
      canvasPatched = true;
      return true;
    };
    this.registerLazyPatcher(patchCanvas);
  }
  registerCanvasExploder() {
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu) => {
        this.exploder.checkAndAddMenu(menu, "Split by headings");
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu) => {
        this.exploder.checkAndAddMenu(menu, "Split by headings");
      })
    );
    this.patchCanvasNodeMenu();
  }
  /**
   * Patches Canvas to add context menu for text nodes (which don't trigger file-menu).
   */
  patchCanvasNodeMenu() {
    const plugin = this;
    this.registerLazyPatcher(() => {
      var _a, _b, _c, _d, _e;
      const canvasView = (_a = this.app.workspace.getLeavesOfType("canvas").find((l) => {
        var _a2, _b2, _c2;
        return (_c2 = (_b2 = (_a2 = l.view) == null ? void 0 : _a2.canvas) == null ? void 0 : _b2.nodes) == null ? void 0 : _c2.size;
      })) == null ? void 0 : _a.view;
      const anyNode = (_e = (_d = (_c = (_b = canvasView == null ? void 0 : canvasView.canvas) == null ? void 0 : _b.nodes) == null ? void 0 : _c.values()) == null ? void 0 : _d.next()) == null ? void 0 : _e.value;
      if (!anyNode)
        return false;
      const basePrototype = Object.getPrototypeOf(Object.getPrototypeOf(anyNode));
      if (!(basePrototype == null ? void 0 : basePrototype.showMenu))
        return false;
      const uninstall = around(basePrototype, {
        showMenu: (next) => {
          return function(menu, ...args) {
            const result = next.call(this, menu, ...args);
            if (this.text !== void 0 && !this.file) {
              plugin.exploder.addTextNodeMenu(menu, this);
            }
            return result;
          };
        }
      });
      this.register(uninstall);
      return true;
    });
  }
  /**
   * Installs hooks into the native Canvas prototype to enable automatic height adjustment behavior,
   * allowing nodes to dynamically resize to fit their content in response to specific user gestures
   * on resize handles.
   */
  patchCanvasNodeAutoHeight() {
    var _a;
    if (this.autoHeightUninstaller)
      return false;
    const canvasView = (_a = this.app.workspace.getLeavesOfType("canvas").find((l) => {
      var _a2, _b, _c;
      return (_c = (_b = (_a2 = l.view) == null ? void 0 : _a2.canvas) == null ? void 0 : _b.nodes) == null ? void 0 : _c.size;
    })) == null ? void 0 : _a.view;
    if (!canvasView)
      return false;
    const canvas = canvasView.canvas;
    if (!canvas)
      return false;
    const anyNode = canvas.nodes.values().next().value;
    if (!anyNode)
      return false;
    const anyNodeConstructor = anyNode.constructor;
    const baseNodePrototype = Object.getPrototypeOf(anyNodeConstructor.prototype);
    const methodsToPatch = {};
    if (baseNodePrototype.onResizeDblclick) {
      methodsToPatch.onResizeDblclick = (originalMethod) => {
        return function(...args) {
          const [, direction] = args;
          if (direction === "bottom") {
            if (this._autoHeightTimer) {
              window.clearTimeout(this._autoHeightTimer);
              this._autoHeightTimer = null;
            }
            this.autoHeightEnabled = true;
          }
          return originalMethod.apply(this, args);
        };
      };
    }
    if (baseNodePrototype.onResizePointerdown) {
      methodsToPatch.onResizePointerdown = (originalMethod) => {
        return function(...args) {
          const [event, direction] = args;
          const result = originalMethod.apply(this, args);
          if (direction === "bottom") {
            if (this._autoHeightTimer) {
              window.clearTimeout(this._autoHeightTimer);
            }
            this._autoHeightTimer = window.setTimeout(() => {
              this.autoHeightEnabled = false;
              this._autoHeightTimer = null;
            }, 300);
          } else if (direction === "right" || direction === "left") {
            if (this.autoHeightEnabled === true) {
              const handlePointerUp = () => {
                window.setTimeout(() => {
                  if (!this.canvas || !this.canvas.nodes.has(this.id))
                    return;
                  if (this.nodeEl && this.nodeEl.classList.contains("is-resizing")) {
                    return;
                  }
                  this.onResizeDblclick(event, "bottom");
                }, 0);
              };
              window.addEventListener("pointerup", handlePointerUp, { once: true });
            }
          }
          return result;
        };
      };
    }
    if (baseNodePrototype.blur) {
      methodsToPatch.blur = (originalMethod) => {
        return function(...args) {
          const result = originalMethod.apply(this, args);
          if (this.autoHeightEnabled) {
            window.setTimeout(() => {
              if (typeof this.onResizeDblclick === "function") {
                const mockEvent = {
                  preventDefault: () => {
                  },
                  stopPropagation: () => {
                  }
                };
                this.onResizeDblclick(mockEvent, "bottom");
              }
            }, 300);
          }
          return result;
        };
      };
    }
    if (Object.keys(methodsToPatch).length === 0)
      return false;
    this.autoHeightUninstaller = around(baseNodePrototype, methodsToPatch);
    this.register(this.autoHeightUninstaller);
    return true;
  }
  registerCanvasNodeAutoHeightPatcher() {
    this.registerLazyPatcher(() => this.patchCanvasNodeAutoHeight());
  }
  /**
   * Writes the user's configured default sizes into a Canvas instance's config so that
   * every native creation path (double-click, paste, programmatic createTextNode/createFileNode)
   * picks them up. Touches in-memory state only.
   */
  applyDefaultNodeSizeToCanvas(canvas) {
    if (!(canvas == null ? void 0 : canvas.config))
      return;
    canvas.config.defaultTextNodeDimensions = {
      width: this.settings.defaultTextNodeWidth,
      height: this.settings.defaultTextNodeHeight
    };
    canvas.config.defaultFileNodeDimensions = {
      width: this.settings.defaultFileNodeWidth,
      height: this.settings.defaultFileNodeHeight
    };
  }
  applyDefaultNodeSizeToAllOpenCanvases() {
    var _a;
    for (const leaf of this.app.workspace.getLeavesOfType("canvas")) {
      const canvas = (_a = leaf.view) == null ? void 0 : _a.canvas;
      if (canvas)
        this.applyDefaultNodeSizeToCanvas(canvas);
    }
  }
  registerCanvasDefaultNodeSize() {
    const apply = () => this.applyDefaultNodeSizeToAllOpenCanvases();
    this.registerEvent(this.app.workspace.on("active-leaf-change", apply));
    this.registerEvent(this.app.workspace.on("layout-change", apply));
    this.app.workspace.onLayoutReady(apply);
    apply();
  }
  /**
   * Patches Canvas.prototype.dragTempNode so dragging a note in from the file explorer
   * uses the user's configured file-node size instead of whatever Obsidian's drag handler
   * computed upstream of canvas.config.
   */
  patchCanvasDragTempNode() {
    var _a, _b, _c;
    if (this.dragTempNodeUninstaller)
      return false;
    const canvasView = (_a = this.app.workspace.getLeavesOfType("canvas").find((l) => {
      var _a2;
      return ((_a2 = l.view) == null ? void 0 : _a2.canvas) != null;
    })) == null ? void 0 : _a.view;
    const canvas = canvasView == null ? void 0 : canvasView.canvas;
    if (!((_c = (_b = canvas == null ? void 0 : canvas.constructor) == null ? void 0 : _b.prototype) == null ? void 0 : _c.dragTempNode))
      return false;
    const plugin = this;
    const uninstall = around(canvas.constructor.prototype, {
      dragTempNode(orig) {
        return function(dragEvent, _nodeSize, onDropped) {
          const overridden = {
            width: plugin.settings.defaultFileNodeWidth,
            height: plugin.settings.defaultFileNodeHeight
          };
          return orig.call(this, dragEvent, overridden, onDropped);
        };
      }
    });
    this.dragTempNodeUninstaller = uninstall;
    this.register(uninstall);
    return true;
  }
  registerCanvasDragTempNodePatcher() {
    this.registerLazyPatcher(() => this.patchCanvasDragTempNode());
  }
  createEdge(node1, node2) {
    const node1CenterX = node1.x + node1.width / 2;
    const node1CenterY = node1.y + node1.height / 2;
    const node2CenterX = node2.x + node2.width / 2;
    const node2CenterY = node2.y + node2.height / 2;
    const angle = Math.atan2(node2CenterY - node1CenterY, node2CenterX - node1CenterX) * 180 / Math.PI;
    const normalizedAngle = angle < 0 ? angle + 360 : angle;
    let fromSide;
    let toSide;
    if (normalizedAngle >= 315 || normalizedAngle < 45) {
      fromSide = "right";
      toSide = "left";
    } else if (normalizedAngle >= 45 && normalizedAngle < 135) {
      fromSide = "bottom";
      toSide = "top";
    } else if (normalizedAngle >= 135 && normalizedAngle < 225) {
      fromSide = "left";
      toSide = "right";
    } else {
      fromSide = "top";
      toSide = "bottom";
    }
    const edgeData = {
      id: randomId(),
      fromSide,
      fromNode: node1.id,
      toSide,
      toNode: node2.id
    };
    return edgeData;
  }
  /**
   * Performs a comprehensive cleanup on all markdown notes when the plugin
   * is unloaded, ensuring any custom properties or data managed by this
   * plugin are removed from the vault.
   */
  onunload() {
    activeDocument.body.classList.remove("enhanced-canvas-enabled");
    this.sendToCanvas.clearSelectedCanvas(false);
    void this.cleanupCanvasProperties();
  }
  /**
   * Strips every plugin-managed property from every markdown note: the
   * `canvas` property plus each per-canvas property (named after a canvas
   * basename). Note-driven rather than canvas-driven so it also removes
   * orphans left behind by deleted/renamed canvases or removed nodes, and
   * it works regardless of `enableFrontmatter`. Returns the paths of notes
   * whose frontmatter could not be updated.
   */
  async cleanupCanvasProperties() {
    const canvasBasenames = new Set(
      this.app.vault.getFiles().filter((file) => file.extension === "canvas").map((file) => file.basename)
    );
    const failedFiles = [];
    await Promise.all(this.app.vault.getMarkdownFiles().map(async (file) => {
      var _a;
      const cached = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
      if (!cached)
        return;
      if (!("canvas" in cached) && !Object.keys(cached).some((key) => canvasBasenames.has(key)))
        return;
      try {
        await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
          if (!frontmatter)
            return;
          for (const link of frontmatterValueToArray(frontmatter.canvas)) {
            delete frontmatter[canvasLinkBasename(link)];
          }
          delete frontmatter.canvas;
          for (const key of Object.keys(frontmatter)) {
            if (canvasBasenames.has(key))
              delete frontmatter[key];
          }
        });
      } catch (error) {
        console.error("Enhanced Canvas: Failed to clean properties from note", file.path, error);
        failedFiles.push(file.path);
      }
    }));
    return failedFiles;
  }
};
var EnhancedCanvasSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian6.Setting(containerEl).setName("Enable Frontmatter Synchronization").setDesc(
      "When enabled, canvas nodes and edges are mapped to file metadata (properties). "
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableFrontmatter).onChange(async (value) => {
        if (!value) {
          this.plugin.settings.enableFrontmatter = false;
          await this.plugin.saveSettings();
          const failedFiles = await this.plugin.cleanupCanvasProperties();
          if (failedFiles.length > 0) {
            new import_obsidian6.Notice(`Failed to clean up properties for ${failedFiles.length} notes. Check console.`);
            this.plugin.settings.enableFrontmatter = true;
            await this.plugin.saveSettings();
            toggle.setValue(true);
          }
          return;
        }
        this.plugin.settings.enableFrontmatter = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Enable Custom Visuals & CSS").setDesc(
      "When enabled, hide the metadata panel (properties) inside Canvas Node (and embedded notes and iframe previews)."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableCustomCSS).onChange(async (value) => {
        this.plugin.settings.enableCustomCSS = value;
        await this.plugin.saveSettings();
        this.plugin.toggleCSSClass(value);
      })
    );
    const MIN_NODE_DIMENSION = 50;
    const MAX_NODE_DIMENSION = 5e3;
    new import_obsidian6.Setting(containerEl).setName("Default node size").setHeading();
    const sizeRow = (name, desc, key) => {
      new import_obsidian6.Setting(containerEl).setName(name).setDesc(desc).addText(
        (text) => text.setValue(String(this.plugin.settings[key])).onChange(async (raw) => {
          const n = Number.parseInt(raw, 10);
          if (!Number.isFinite(n))
            return;
          if (n < MIN_NODE_DIMENSION || n > MAX_NODE_DIMENSION)
            return;
          this.plugin.settings[key] = n;
          await this.plugin.saveSettings();
          this.plugin.applyDefaultNodeSizeToAllOpenCanvases();
        })
      );
    };
    sizeRow("Text node width", "Initial width (px) for new text cards. 50\u20135000.", "defaultTextNodeWidth");
    sizeRow("Text node height", "Initial height (px) for new text cards. 50\u20135000.", "defaultTextNodeHeight");
    sizeRow("File node width", "Initial width (px) for new file nodes. 50\u20135000.", "defaultFileNodeWidth");
    sizeRow("File node height", "Initial height (px) for new file nodes. 50\u20135000.", "defaultFileNodeHeight");
  }
};


/* nosourcemap */